

export const TYPES={
    ADD_USUARIO:'ADD_USUARIO',
    REMOVE_USUARIO:'REMOVE_USUARIO',
    UPDATE_USUARIO:'UPDATE_USUARIO',
    GET_USUARIO:'GET_USUARIO',
    CHANGE_SHOW_LOADING:'CHANGE_SHOW_LOADING',
    SHOW_LOADING:'SHOW_LOADING',
    DISPOSE_LOADING:'DISPOSE_LOADING',
}